### ISSUE TITLE
DockerFile GPT4ALL non présent

### ISSUE THREAD

**Issue by scenaristeur** [etalab-ia/albert#12]
La doc https://github.com/etalab-ia/albert/blob/main/docs/fr/installation.md#avec-docker
 fait référence dans la section sans GPU à un DockerFile qui n'existe pas https://github.com/etalab-ia/albert/blob/main/docs/contrib/gpt4all/Dockerfile

**Comment by dtrckd** [comment]
Le liens vers cette doc semble périmé en effet.
Le fichier existe bien ici https://github.com/etalab-ia/albert/tree/main/contrib/gpt4all
@bolinocroustibat @leoguillaume

**Comment by scenaristeur** [comment]
@dtrckd ok, du coup il faut lancer le build avec 

`docker build --tag albert/llm:latest --build-context pyalbert=./pyalbert --file ./contrib/gpt4all/Dockerfile ./contrib/gpt4all`
ou 
`docker build --tag albert/llm:latest --build-context pyalbert=./pyalbert --file ./contrib/gpt4all/Dockerfile ./llm`

??

**Comment by bolinocroustibat** [comment]
> La doc https://github.com/etalab-ia/albert/blob/main/docs/fr/installation.md#avec-docker
fait référence dans la section sans GPU à un DockerFile qui n'existe pas https://github.com/etalab-ia/albert/blob/main/docs/contrib/gpt4all/Dockerfile

Bien vu, c'est corrigé.

**Comment by dtrckd** [comment]
@scenaristeur l'option une du coup pour gpt4all.

**Comment by bolinocroustibat** [comment]
Fixed: https://github.com/etalab-ia/albert/commit/2aa6ff5be2a3118cbe76e7cf25ed90cbeec2f2c7
Thanks @scenaristeur
