### ISSUE TITLE
Albert confusion de nom de projet possible

### ISSUE THREAD

**Issue by scenaristeur** [etalab-ia/albert#9]
Bonjour, n'y a-t-il pas possible confusion de nom entre votre projet Albert et le projet https://huggingface.co/docs/transformers/model_doc/albert, ou encore tous les autres Albert ??? 
https://huggingface.co/models?other=albert

**Comment by bolinocroustibat** [comment]
Il y a effectivement plusieurs project homonymes, celui-ci a été développé par des agents publics au sein d'Etalab. Comme un certain nombre d'autres modèles développés par les agents publics, il est disponible sur https://huggingface.co/AgentPublic
